import Head from 'next/head';
import { useEffect, useState } from 'react';

export default function Home() {
  const [data, setData] = useState();

  async function getData() {
    const response = await fetch('/api/hello');
    const parsedResponse = await response.json();
    setData(parsedResponse);
  }

  useEffect(() => {
    getData();
  }, []);

  if (!data) {
    return <div>no data yet</div>;
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>{data.name}</main>
    </div>
  );
}
